export const DEFAULT_SETTINGS = {
  fullName: 'Atif Ayyoub',
  heroTitle: 'AI Web & Custom Software Developer',
  heroSubtitle: 'Building modern web, AI, and custom software experiences.',
  aboutHeading: 'About Me',
  aboutDescription: 'Get to know me better',
  professionalTitle: 'AI Web & Custom Software Developer',
  email: 'atifayyoub82@gmail.com',
  phone: '+923270728950',
  address: 'Pakistan',
  nationality: 'Pakistan',
  languages: 'English, Urdu, Punjabi',
  resumeLink: '',
  profileImage: '/Atif.png',
  heroImage: '/Atif1.png',
  introLine: "Hi, I\'m Atif Ayyoub",
  professionalTagline: 'Consistency Makes a Man Perfect in Their Skill Set.',
  aboutContent:
    'I’m a passionate and results driven professional who believes in delivering quality work that truly makes an impact. With a strong background in technology, design, and digital innovation, I specialize in creating practical, high performing solutions tailored to each client’s unique goals. I take pride in clear communication, creative problem solving, and a commitment to exceeding expectations on every project. My focus is always on building long-term partnerships through reliability, professionalism, and exceptional results.',
}

export const DEFAULT_SOCIAL_LINKS = [
  { id: 'social-linkedin', platform: 'LinkedIn', url: 'https://www.linkedin.com', icon: 'linkedin', isActive: true, displayOrder: 1 },
  { id: 'social-github', platform: 'GitHub', url: 'https://github.com', icon: 'github', isActive: true, displayOrder: 2 },
  { id: 'social-twitter', platform: 'Twitter / X', url: 'https://twitter.com', icon: 'twitter', isActive: true, displayOrder: 3 },
  { id: 'social-youtube', platform: 'YouTube', url: 'https://www.youtube.com', icon: 'youtube', isActive: true, displayOrder: 4 },
]

export const DEFAULT_SERVICES = [
  {
    id: 'service-ui-ux',
    title: 'UI/UX Design',
    shortDescription: 'Crafting intelligent UI/UX experiences with AI-powered design thinking.',
    fullDescription:
      'I build clean, modern interfaces supported by smart visual systems and prototypes. Every design balances aesthetics, usability, and functionality for web and mobile products.',
    icon: 'palette',
    rate: '$20/hour',
    category: 'Design',
    displayOrder: 1,
    isActive: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-web-dev',
    title: 'Web Development',
    shortDescription: 'Building modern, responsive, and high-performance websites.',
    fullDescription:
      'I develop scalable web applications using clean and efficient code, focused on secure, fast, and user-friendly digital experiences.',
    icon: 'code',
    rate: '$20/hour',
    category: 'Development',
    displayOrder: 2,
    isActive: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-mobile',
    title: 'Mobile App Development',
    shortDescription: 'High-performance mobile apps with clean maintainable code.',
    fullDescription:
      'Specialized in responsive designs and seamless interactions using modern frameworks to deliver scalable mobile solutions.',
    icon: 'mobile',
    rate: '$20/hour',
    category: 'Development',
    displayOrder: 3,
    isActive: true,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-desktop',
    title: 'Desktop App Development',
    shortDescription: 'Robust desktop applications for Windows, Mac, and Linux.',
    fullDescription:
      'From concept to deployment, I deliver reliable desktop solutions that turn complex workflows into intuitive experiences.',
    icon: 'desktop',
    rate: '$20/hour',
    category: 'Development',
    displayOrder: 4,
    isActive: true,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-ai-integration',
    title: 'AI Integration',
    shortDescription: 'Integrating AI capabilities into products for smarter workflows and automation.',
    fullDescription:
      'I add practical AI features such as chat assistants, workflow automation, and intelligent recommendations tailored to your business use-case.',
    icon: 'code',
    rate: '$25/hour',
    category: 'AI Tools',
    displayOrder: 5,
    isActive: true,
    featured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-api-dev',
    title: 'API Development',
    shortDescription: 'Secure and scalable APIs for web, mobile, and third-party integrations.',
    fullDescription:
      'I design and develop REST APIs with clean architecture, robust validation, and clear documentation for long-term maintainability.',
    icon: 'desktop',
    rate: '$22/hour',
    category: 'APIs',
    displayOrder: 6,
    isActive: true,
    featured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const DEFAULT_PROJECTS = [
  {
    id: 'project-wallpaper-hub',
    title: 'Wallpaper Hub',
    shortDescription: 'Laravel-powered web app for browsing, categorizing and downloading high-quality wallpapers.',
    fullDescription:
      'Built with Laravel and MySQL. Supports user uploads, fast search, categories, and optimized image delivery for responsive viewing and downloads.',
    thumbnail: '/Wallpaper Hub.png',
    galleryImages: [],
    technologies: ['Laravel', 'PHP', 'MySQL'],
    category: 'Web Apps',
    liveUrl: '',
    githubUrl: 'https://github.com/Atif327/Wallhub',
    caseStudyUrl: '',
    projectStatus: 'completed',
    featured: true,
    displayOrder: 1,
    isActive: true,
    startDate: '',
    endDate: '',
    clientName: '',
    role: 'Full Stack Developer',
    highlights: 'High quality image delivery, fast filtering, responsive UI.',
    challengesSolutions: 'Improved loading speed with optimized image rendering and structured categories.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'project-task-manager',
    title: 'Task Manager',
    shortDescription: 'Flutter app for creating, organizing and tracking tasks and subtasks.',
    fullDescription:
      'Built with Dart and SQLite with reminders, priorities, and progress tracking for offline-first productivity.',
    thumbnail: '/Task Manager.jpeg',
    galleryImages: [],
    technologies: ['Flutter', 'Dart', 'SQLite'],
    category: 'Mobile Apps',
    liveUrl: '',
    githubUrl: '',
    caseStudyUrl: '',
    projectStatus: 'completed',
    featured: true,
    displayOrder: 2,
    isActive: true,
    startDate: '',
    endDate: '',
    clientName: '',
    role: 'Mobile Developer',
    highlights: 'Offline-first architecture and simple UX.',
    challengesSolutions: 'Handled local state complexity with structured task model.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'project-student-evaluation',
    title: 'Student Evaluation System',
    shortDescription: 'React + Node.js platform for managing assessments and attendance.',
    fullDescription:
      'Uses SQLite storage and provides grade entry, analytics, and exportable summaries for instructors.',
    thumbnail: '/Student Evalution System.png',
    galleryImages: [],
    technologies: ['React', 'Node.js', 'SQLite'],
    category: 'Web Apps',
    liveUrl: '',
    githubUrl: '',
    caseStudyUrl: '',
    projectStatus: 'completed',
    featured: false,
    displayOrder: 3,
    isActive: true,
    startDate: '',
    endDate: '',
    clientName: '',
    role: 'Full Stack Developer',
    highlights: 'Assessment workflows, attendance tracking, reports.',
    challengesSolutions: 'Reduced manual reporting through export-ready summaries.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const DEFAULT_MESSAGES = []
